### ISSUE TITLE
Render after transparents?

### ISSUE THREAD

**Issue by SamFZGames** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#13]
Hello! Wonderful plugin. Is there a way of getting this to render after transparency? I mostly wanted to use this for water rather than cube maps but it appears to render after opaquest but before transparency.

**Comment by JoshuaLim007** [comment]
Hi, the tricky part of applying reflections to transparent objects is that unity renders the gbuffers without any transparent objects. So the depth buffer along with the other buffers won't have information about the transparent objects. I may have a possible workaround for it. Be on the look out for an update.

**Comment by SamFZGames** [comment]
That’s awesome, thanks! Yeah I could just do with the ability to have a transparent surface receive SSR like in the HDRP, (in this case, a flat plane of water, where my shader which uses the opaque texture for transparency(refraction), not so much whether the transparent surfaces themselves reflect. Currently I just use cube maps but it would be really nice to get some accurate reflections on the surface.

Wonderful work already, by the way!

**Comment by JoshuaLim007** [comment]
Ok, I don't there is a solution to this with the current implementation. I've tried to modify the gbuffer and the depth buffer to include the transparent objects but that will break transparency. I have attempted to make my own depth buffer that contains the depth of the transparent objects along with a custom gbuffer but that gets convoluted. Basically, doubling the texture sampling in the hi-z depth pass and the ssr pass. This reduced performance. I do have a possible solution but that will require a total rework, if anyone wants to implement themselves go ahead. Moving the SSR reflection into the surface shader itself can solve this limitation. Doom eternal does exactly this with a forward path pipeline. [Doom Eternal Study](https://simoncoenen.com/blog/programming/graphics/DoomEternalStudy). This implementation can both support reflections on transparent objects and forward shading pipelines. The idea is to perform a SSR pass when rendering individual objects rather than a full screen effect.

**Comment by SamFZGames** [comment]
I understand. Thank you so much for taking the time to try it anyway! I will use cube maps for my water, but will continue using your SSR for opaques as it’s really great, and has really elevated my project. Thank you! (Thanks for the Doom Eternal study link too.)
