### ISSUE TITLE
Depth Pyramid breaks Rendering Debugger

### ISSUE THREAD

**Issue by Milk-Drinker01** [JoshuaLim007/Unity-ScreenSpaceReflections-URP#14]
When debugging lighting using the rendering debugger (window > analysis > rendering debugger), rendering completely breaks with the depth pyramid enabled. 

https://user-images.githubusercontent.com/59656122/234104049-d261b3d0-c3c1-467a-8df6-82e049f7e399.mp4

**Comment by JoshuaLim007** [comment]
Just tested this. It seems to break only in URP 14 and not in URP 12.

**Comment by Milk-Drinker01** [comment]
I wonder if its possible to tell if the rendering debugger is active? Its probably just easier to disable the depth pyramid while its running. 
Also, Its broken on URP 16 as well. Classic unity

**Comment by jiaozi158** [comment]
Hi, just found this great repo.

Rendering debugger forces Forward path because the debug outputs are in "UniversalForward" shader pass.

It's possible to detect the rendering debugger window with  `DebugManager.instance.isAnyDebugUIActive`

This should return false if there's no rendering debugger window opened.

**Comment by JoshuaLim007** [comment]
Fixed this issue with the newest PR.
